### ISSUE TITLE
3.0.4 version doesn't download any torrents

### ISSUE THREAD

**Issue by TheMiracleExpress** [TorrentChecker/TorrentChecker#1]
3.0.4 version (as well as previos 2.x.x version) doesn't download any torrents from rutracker.org starting August 3. Some users report "parsing error".

**Comment by TorrentChecker** [comment]
yep, will be fixed soon

**Comment by TorrentChecker** [comment]
https://github.com/TorrentChecker/TorrentChecker/commit/b1de011acaa857f16022ed5faf1d6ee7c430a8ea
